// ARCHIVO GENERADO AUTOMÁTICAMENTE - NO EDITAR A MANO
const productos = [
{
                id: 1,
                nombre: "Chaqueta de mezclilla Chrome hearts 0002",
                marca: "chrome-hearts",
                categoria: ["chaquetas", "mezclilla"],
                precioMenudeo: 1200,
                precioMayoreo: 1100,
                precioDistribuidor: 900,
                tallas: ["S", "M", "L", "XL"],
                colores: ["Mezclilla azul"],
                descripcion: "Chaqueta de mezclilla con 2 bolsas en el pecho. Botones con el diseño de la marca. Parches de piel con relieve y diseño de la marca. Costuras de excelente calidad, con etiquetas internas y externas de la marca y bolsa chrome hearts.",
                    imagen: [
            "productos/0001/100.jpg",
            "productos/0001/101.jpg",
            "productos/0001/102.jpg",
            "productos/0001/103.jpg",
            "productos/0001/104.jpg",
            "productos/0001/105.jpg",
            "productos/0001/106.jpg",
            
        ]
            },
             {
                id: 2,
                nombre: "Chaqueta de mezclilla Chrome hearts 0001",
                marca: "chrome-hearts",
                categoria: ["chaquetas", "mezclilla"],
                precioMenudeo: 1200,
                precioMayoreo: 1100,
                precioDistribuidor: 900,
                tallas: ["S", "M", "L", "XL"],
                colores: ["Mezclilla negra"],
                descripcion: "Chaqueta de mezclilla con 2 bolsas en el pecho. Botones con el diseño de la marca. Parches de mezclilla con relieve y diseño de la marca. Costuras de excelente calidad, con etiquetas internas y externas de la marca y bolsa chrome hearts",
                    imagen: [
            "productos/0002/100.jpg",
            "productos/0002/101.jpg",
            "productos/0002/102.jpg",
            "productos/0002/103.jpg",
            "productos/0002/104.jpg",
            "productos/0002/105.jpg"
        ]
            },
            {
                id: 3,
                nombre: "Chaqueta de mezclilla Chrome hearts 0003",
                marca: "chrome-hearts",
                categoria: ["chaquetas", "mezclilla"],
                precioMenudeo: 1220,
                precioMayoreo: 1120,
                precioDistribuidor: 920,
                tallas: ["S", "M", "L", "XL"],
                colores: ["Mezclilla negra"],
                descripcion: "Chaqueta de mezclilla con 2 bolsas en el pecho. Botones con el diseño de la marca. Parches piel con relieve del diseño de la marca y simbolos. Costuras de excelente calidad, con etiquetas internas y externas de la marca y bolsa chrome hearts",
                    imagen: [
            "productos/0003/100.jpg",
            "productos/0003/101.jpg",
            "productos/0003/102.jpg",
            "productos/0003/103.jpg"
        ]
        
            },
             {
                id: 4,
                nombre: "Chamarra reversible Chrome hearts 0004",
                marca: "chrome-hearts",
                categoria: ["chamarras", "mezclilla"],
                precioMenudeo: 1500,
                precioMayoreo: 1300,
                precioDistribuidor: 1000,
                tallas: ["S", "M", "L", "XL"],
                colores: ["Gris reversible a negra"],
                descripcion: "Chamarra de algodon reversible. cierre con el diseño de la marca. el lado revercible tiene la tela holograma de la marca. Costuras de excelente calidad, con etiquetas internas y externas de la marca y bolsa chrome hearts",
                    imagen: [
            "productos/0004/100.jpg",
            "productos/0004/101.jpg",
            "productos/0004/102.jpg",
            "productos/0004/103.jpg",
            "productos/0004/104.jpg"
        ]
            },
          {
        id: 5,
        nombre: "Cardigan Chrome hearts 0005",
        marca: "chrome-hearts",
        categoria: ["cardigan"],
        precioMenudeo: 1150,
        precioMayoreo: 1050,
        precioDistribuidor: 850,
        tallas: ["S", "M", "L", "XL"],
        colores: ["negro", "gris", "beige"],
        descripcion: "Cardigan con 2 bolsas. Botones con el diseño de la marca. Parches de piel con relieve y diseño de la marca. Costuras de excelente calidad, con etiquetas internas y externas de la marca.",
        imagen: [
            "productos/0005/1.jpeg",
            "productos/0005/2.jpeg",
            "productos/0005/3.jpeg",
            "productos/0005/4.jpeg",
            "productos/0005/5.jpeg",
            "productos/0005/6.jpeg",
            "productos/0005/7.jpeg",
            "productos/0005/8.jpeg"
        ],
        // ✨ AQUÍ ESTÁ LA MAGIA NUEVA (LAS PAREJITAS) ✨
        variantes: [
            { nombre: "negro", imagen: "productos/chrome-hearts/0005/1.jpeg" },
            { nombre: "beige", imagen: "productos/chrome-hearts/0005/5.jpeg" },
            { nombre: "gris",  imagen: "productos/chrome-hearts/0005/7.jpeg" }
        ],
        guiaTallas: "productos/chrome-hearts/0005/9.png"
    },
             {
                id: 6,
                nombre: "Playera Chrome hearts 0006",
                marca: "chrome-hearts",
                categoria: ["playeras"],
                precioMenudeo: 1050,
                precioMayoreo: 900,
                precioDistribuidor: 800,
                tallas: ["S", "M", "L", "XL"],
                colores: ["negro", "gris"],
                descripcion: "Playera de textura tipo waffle. Botones con el diseño de la marca. Parches de piel con relieve y diseño de la marca. Costuras de excelente calidad, con etiquetas internas y externas de la marca y bolsa chrome hearts",
                    imagen: [
            "productos/0006/1.jpeg",
            "productos/0006/2.jpeg",
            "productos/0006/3.jpeg",
            "productos/0006/4.jpeg",
            "productos/0006/5.jpeg",
            "productos/0006/6.jpeg",
            "productos/0006/7.jpeg"
        ]
            },
            {
                id: 7,
                nombre: "Chamarra Chrome hearts 0007",
                marca: "chrome-hearts",
                categoria: ["chamarras"],
                precioMenudeo: 1200,
                precioMayoreo: 1100,
                precioDistribuidor: 900,
                tallas: ["S", "M", "L", "XL"],
                colores: ["negro"],
                descripcion: "Chamarra de tipo punto con 2 bolsas enfrente. cierre con el diseño de la marca. Parches piel con relieve del diseño de la marca y simbolos. Costuras de excelente calidad, con etiquetas internas y externas de la marca y bolsa chrome hearts",
                    imagen: [
            "productos/0007/1.jpeg",
            "productos/0007/2.jpeg",
            "productos/0007/3.jpeg",
            "productos/0007/4.jpeg",
            "productos/0007/5.jpeg"
        ]
        
            },
             {
                id: 8,
                nombre: "Sueter Chrome hearts 0009",
                marca: "chrome-hearts",
                categoria: ["sueters"],
                precioMenudeo: 1100,
                precioMayoreo: 1000,
                precioDistribuidor: 830,
                tallas: ["S", "M", "L", "XL"],
                colores: ["negro"],
                descripcion: "sueter punto. diseño de bocas en las mangas del sueter. En la parte tracera lleva cosidos parches de cuero de cruces rojas y el logo de la marca. Costuras de excelente calidad, con etiquetas internas y externas de la marca y bolsa chrome hearts",
                    imagen: [
            "productos/0008/1.jpeg",
            "productos/0008/2.jpeg",
            "productos/0008/3.jpeg",
            "productos/0008/4.jpeg"
        ]

            },
            {
                id: 9,
                nombre: "Sueter Chrome hearts 0009",
                marca: "chrome-hearts",
                categoria: ["sueters"],
                precioMenudeo: 1150,
                precioMayoreo: 950,
                precioDistribuidor: 800,
                tallas: ["S", "M", "L", "XL"],
                colores: ["negro"],
                descripcion: "Sueter de punto con diseño de cruces y logos de la marca. Costuras de excelente calidad, con etiquetas internas y externas de la marca y bolsa chrome hearts",
                    imagen: [
            "productos/0009/1.jpg",
            "productos/0009/2.jpeg",
            "productos/0009/3.jpeg",
            "productos/0009/4.jpeg",
            "productos/0009/5.jpeg"
        ]
        
            },
            {
                id: 10,
                nombre: "Sueter Chrome hearts 0010",
                marca: "chrome-hearts",
                categoria: ["sueters"],
                precioMenudeo: 1070,
                precioMayoreo: 970,
                precioDistribuidor: 810,
                tallas: ["S", "M", "L", "XL"],
                colores: ["negro"],
                descripcion: "sueter de tipo punto. Parches piel roja con relieve del diseño de la marca y simbolos. Costuras de excelente calidad, con etiquetas internas y externas de la marca y bolsa chrome hearts",
                    imagen: [
            "productos/0010/1.jpeg",
            "productos/0010/2.jpeg",
            "productos/0010/3.jpeg",
            "productos/0010/4.jpeg",
            "productos/0010/5.jpeg"
        ]
        
            },
{
    id: 11,
    codigo: "0011",
    nombre: "sueter chrome hearts de punto ",
    marca: "chrome-hearts",
    link: "https://www.kakobuy.com/item/details?url=https%3A%2F%2Fdetail.1688.com%2Foffer%2F987698227996.html%3Fsource_type%3Dimage",
    categoria: ["sueters"],
    precioMenudeo: 1070,
    precioMayoreo: 970,
    precioDistribuidor: 810,
    tallas: ["s","m","l","xl"],
    colores: ["negro","gris","beige"],
    descripcion: "sueter de punto chrome hearts, de materiales de algodon con insignias de metal en la parte del pecho, el cuello y en la parte de atras con detalles de desgaste en la parte de enfrente y en los bordes",
    imagen: [
        'productos/0011/1.jpeg',
        'productos/0011/2.jpeg',
        'productos/0011/3.jpeg',
        'productos/0011/4.jpeg',
        'productos/0011/5.jpeg',
        'productos/0011/6.jpeg',
        'productos/0011/7.jpeg',
        'productos/0011/8.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0011/1.jpeg" },
        { nombre: "gris", imagen: "productos/0011/5.jpeg" },
        { nombre: "beige", imagen: "productos/0011/7.jpeg" }
    ],
},
{
    id: 12,
    codigo: "0012",
    nombre: "supreme backpack ss20 0012",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 870,
    precioMayoreo: 770,
    precioDistribuidor: 670,
    tallas: [],
    colores: ["negro","rojo","azul"],
    descripcion: "supreme backpack ss20 de materiales de tela cordura de 610d y malla de pvc, de 25 litros y capacidad de laptop de 13 pulgadas, con 4 cierres y 4 compartimentos básicos",
    imagen: [
        'productos/0012/1.jpeg',
        'productos/0012/2.jpeg',
        'productos/0012/3.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0012/1.jpeg" },
        { nombre: "rojo", imagen: "productos/0012/2.jpeg" },
        { nombre: "azul", imagen: "productos/0012/3.jpeg" }
    ],
    guiaTallas: "productos/0012/guia.jpeg"
},
{
    id: 13,
    codigo: "0013",
    nombre: "supreme shoulder bag fw22 0013",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 460,
    precioMayoreo: 410,
    precioDistribuidor: 360,
    tallas: [],
    colores: ["negro","verde","rojo","gris"],
    descripcion: "supreme shoulder bag fw22 de materiales de lona y nailon resistente al agua (cordura recor), de 1.5 litros de capacidad, con 2 cierres y 4 compartimentos.",
    imagen: [
        'productos/0013/1.jpeg',
        'productos/0013/2.jpeg',
        'productos/0013/3.jpeg',
        'productos/0013/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0013/1.jpeg" },
        { nombre: "verde", imagen: "productos/0013/2.jpeg" },
        { nombre: "rojo", imagen: "productos/0013/3.jpeg" },
        { nombre: "gris", imagen: "productos/0013/4.jpeg" }
    ],
},
{
    id: 14,
    codigo: "0014",
    nombre: "supreme mesh zip tote ss20 0014",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 800,
    precioMayoreo: 700,
    precioDistribuidor: 610,
    tallas: [],
    colores: ["negro","azul","rojo","gris"],
    descripcion: "supreme mesh zip tote ss20 de materiales de nylon y malla, de 25 litros y capacidad de laptop de hasta 15 pulgadas, con 1 cierre principal y 4 compartimentos",
    imagen: [
        'productos/0014/1.jpeg',
        'productos/0014/2.jpeg',
        'productos/0014/3.jpeg',
        'productos/0014/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0014/1.jpeg" },
        { nombre: "azul", imagen: "productos/0014/2.jpeg" },
        { nombre: "rojo", imagen: "productos/0014/3.jpeg" },
        { nombre: "gris", imagen: "productos/0014/4.jpeg" }
    ],
},
{
    id: 15,
    codigo: "0015",
    nombre: "supreme waist bag ss20 0015",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 540,
    precioMayoreo: 440,
    precioDistribuidor: 410,
    tallas: [],
    colores: ["negro","rojo","amarillo","azul"],
    descripcion: "supreme waist bag ss20 de materiales de lona cordura y malla con recubrimiento de pvc, de 6 litros de capacidad, con un logotipo reflectante de 3m, 2 hebillas frontales ajustables y 4 compartimentos",
    imagen: [
        'productos/0015/1.jpeg',
        'productos/0015/2.jpeg',
        'productos/0015/3.jpeg',
        'productos/0015/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0015/1.jpeg" },
        { nombre: "rojo", imagen: "productos/0015/2.jpeg" },
        { nombre: "amarillo", imagen: "productos/0015/3.jpeg" },
        { nombre: "azul", imagen: "productos/0015/4.jpeg" }
    ],
},
{
    id: 16,
    codigo: "0016",
    nombre: "supreme mini duffle bag ss24 0016",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 570,
    precioMayoreo: 470,
    precioDistribuidor: 430,
    tallas: [],
    colores: ["negro","azul","verde","naranja"],
    descripcion: "supreme mini duffle bag ss24 de materiales de nylon cordura 500d y rejilla poli ripstop reflectante 3m, de 5.5 litros de capacidad, con 3 cierres de cremallera y 4 compartimentos externos principales",
    imagen: [
        'productos/0016/1.jpeg',
        'productos/0016/2.jpeg',
        'productos/0016/3.jpeg',
        'productos/0016/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0016/1.jpeg" },
        { nombre: "azul", imagen: "productos/0016/2.jpeg" },
        { nombre: "verde", imagen: "productos/0016/3.jpeg" },
        { nombre: "naranja", imagen: "productos/0016/4.jpeg" }
    ],
},
{
    id: 17,
    codigo: "0017",
    nombre: "supreme backpack fw18 0017",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 840,
    precioMayoreo: 740,
    precioDistribuidor: 640,
    tallas: [],
    colores: ["negro","morado","rojo","amarillo"],
    descripcion: "supreme backpack fw18 de materiales de nailon cordura resistente al agua y malla, de 24 litros y capacidad de laptop de 15 pulgadas, con 3 cierres y 4 compartimentos.",
    imagen: [
        'productos/0017/1.jpeg',
        'productos/0017/2.jpeg',
        'productos/0017/3.jpeg',
        'productos/0017/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0017/1.jpeg" },
        { nombre: "morado", imagen: "productos/0017/2.jpeg" },
        { nombre: "rojo", imagen: "productos/0017/3.jpeg" },
        { nombre: "amarillo", imagen: "productos/0017/4.jpeg" }
    ],
},
{
    id: 18,
    codigo: "0018",
    nombre: "supreme backpack ss19 0018",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 860,
    precioMayoreo: 760,
    precioDistribuidor: 660,
    tallas: [],
    colores: ["negro","verde","rojo","aqua"],
    descripcion: "supreme backpack ss19 de materiales de nailon cordura con diseño jacquard, de 25 litros y capacidad de laptop de 15.6 pulgadas, con 3 cierres principales y 4 compartimentos internos y externos",
    imagen: [
        'productos/0018/1.jpeg',
        'productos/0018/2.jpeg',
        'productos/0018/3.jpeg',
        'productos/0018/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0018/1.jpeg" },
        { nombre: "verde", imagen: "productos/0018/2.jpeg" },
        { nombre: "rojo", imagen: "productos/0018/3.jpeg" },
        { nombre: "aqua", imagen: "productos/0018/4.jpeg" }
    ],
},
{
    id: 19,
    codigo: "0019",
    nombre: "backpack supreme x the north face fw20 0019",
    marca: "supreme, north-face",
    categoria: ["mochilas"],
    precioMenudeo: 860,
    precioMayoreo: 760,
    precioDistribuidor: 650,
    tallas: [],
    colores: ["negro"],
    descripcion: "mochila supreme x the north face fw20 de materiales de nylon cordura 630d resistente al agua, de 30 litros de capacidad, con 2 bolsillos laterales con cierre y 1 compartimento principal amplio.",
    imagen: [
        'productos/0019/1.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0019/1.jpeg" }
    ],
},
{
    id: 20,
    codigo: "0020",
    nombre: "supreme backpack ss24 0020",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 860,
    precioMayoreo: 760,
    precioDistribuidor: 650,
    tallas: [],
    colores: ["negro","azul","camuflaje","naranja"],
    descripcion: "supreme backpack ss24 de materiales de nylon cordura 500d y poliéster reflectante 3m ripstop resistente al agua, de 23 litros y compartimento principal con funda sencilla para laptop, con 4 cierres exteriores principales",
    imagen: [
        'productos/0020/1.jpeg',
        'productos/0020/2.jpeg',
        'productos/0020/3.jpeg',
        'productos/0020/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0020/1.jpeg" },
        { nombre: "azul", imagen: "productos/0020/2.jpeg" },
        { nombre: "camuflaje", imagen: "productos/0020/3.jpeg" },
        { nombre: "naranja", imagen: "productos/0020/4.jpeg" }
    ],
},
{
    id: 21,
    codigo: "0021",
    nombre: "supreme backpack fw21 0021",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 860,
    precioMayoreo: 760,
    precioDistribuidor: 650,
    tallas: [],
    colores: ["negro","rojo","blanco","verde"],
    descripcion: "supreme backpack fw21 de materiales de nylon ripstop reciclado y cordura resistente al agua, de 20 litros y capacidad de laptop de hasta 15 pulgadas o 16 pulgadas, con 3 cierres principales externos y 4 compartimentos ",
    imagen: [
        'productos/0021/1.jpeg',
        'productos/0021/2.jpeg',
        'productos/0021/3.jpeg',
        'productos/0021/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0021/1.jpeg" },
        { nombre: "rojo", imagen: "productos/0021/2.jpeg" },
        { nombre: "blanco", imagen: "productos/0021/3.jpeg" },
        { nombre: "verde", imagen: "productos/0021/4.jpeg" }
    ],
},
{
    id: 22,
    codigo: "0022",
    nombre: "supreme backpack ss22 0022",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 860,
    precioMayoreo: 760,
    precioDistribuidor: 650,
    tallas: [],
    colores: ["negro","gris","rojo"],
    descripcion: "supreme backpack ss22 de materiales de nylon ripstop reciclado y malla cordura resistente al agua, de 23 litros y capacidad de laptop con funda de una sola capa, con 2 cierres principales y 3 compartimentos",
    imagen: [
        'productos/0022/1.jpeg',
        'productos/0022/2.jpeg',
        'productos/0022/3.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0022/1.jpeg" },
        { nombre: "gris", imagen: "productos/0022/2.jpeg" },
        { nombre: "rojo", imagen: "productos/0022/3.jpeg" }
    ],
},
{
    id: 23,
    codigo: "0023",
    nombre: "mochila supreme ss22 reign 23 0023",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 860,
    precioMayoreo: 760,
    precioDistribuidor: 650,
    tallas: [],
    colores: ["negro","blanco","rosa","cafe"],
    descripcion: "mochila supreme ss22 reign 23 de materiales de nailon cordura® y malla, de 22 litros y capacidad de laptop de 15 pulgadas, con 3 cierres y 3 compartimentos principales más bolsillos organizadores internos y red exterior.",
    imagen: [
        'productos/0023/1.jpeg',
        'productos/0023/2.jpeg',
        'productos/0023/3.jpeg',
        'productos/0023/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0023/1.jpeg" },
        { nombre: "blanco", imagen: "productos/0023/2.jpeg" },
        { nombre: "rosa", imagen: "productos/0023/3.jpeg" },
        { nombre: "cafe", imagen: "productos/0023/4.jpeg" }
    ],
},
{
    id: 24,
    codigo: "0024",
    nombre: "supreme leather backpack fw24 0024",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 880,
    precioMayoreo: 780,
    precioDistribuidor: 670,
    tallas: [],
    colores: ["cafe","negro","rojo","verde"],
    descripcion: "supreme leather backpack fw24 de materiales de piel de vacuno con forro de satén, de 22 litros y capacidad de laptop de 15 pulgadas, con 3 cierres y 4 compartimentos",
    imagen: [
        'productos/0024/1.jpeg',
        'productos/0024/2.jpeg',
        'productos/0024/3.jpeg',
        'productos/0024/4.jpeg'
    ],
    variantes: [
        { nombre: "cafe", imagen: "productos/0024/1.jpeg" },
        { nombre: "negro", imagen: "productos/0024/2.jpeg" },
        { nombre: "rojo", imagen: "productos/0024/3.jpeg" },
        { nombre: "verde", imagen: "productos/0024/4.jpeg" }
    ],
},
{
    id: 25,
    codigo: "0025",
    nombre: "mochila supreme x the north face 0025",
    marca: "supreme, north-face",
    categoria: ["mochilas"],
    precioMenudeo: 920,
    precioMayoreo: 820,
    precioDistribuidor: 700,
    tallas: [],
    colores: ["negro","azul","rosa","verde"],
    descripcion: "mochila supreme x the north face summit series rescue chugach 16 de materiales de nylon reciclado 420d y nylon balístico 840d, de 16 litros y compartimento interno para laptop, con parches reflectantes 3m, 3 cierres principales y organizador interno.",
    imagen: [
        'productos/0025/1.jpeg',
        'productos/0025/2.jpeg',
        'productos/0025/3.jpeg',
        'productos/0025/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0025/1.jpeg" },
        { nombre: "azul", imagen: "productos/0025/2.jpeg" },
        { nombre: "rosa", imagen: "productos/0025/3.jpeg" },
        { nombre: "verde", imagen: "productos/0025/4.jpeg" }
    ],
},
{
    id: 26,
    codigo: "0026",
    nombre: "supreme waist bag ss18 0026",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 510,
    precioMayoreo: 460,
    precioDistribuidor: 390,
    tallas: [],
    colores: ["negro","rojo","cafe","azul"],
    descripcion: "supreme waist bag ss18 de materiales de lona cordura® ripstop y nylon, de 4 litros de capacidad, con 2 cierres y 2 compartimentos.",
    imagen: [
        'productos/0026/1.jpeg',
        'productos/0026/2.jpeg',
        'productos/0026/3.jpeg',
        'productos/0026/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0026/1.jpeg" },
        { nombre: "rojo", imagen: "productos/0026/2.jpeg" },
        { nombre: "cafe", imagen: "productos/0026/3.jpeg" },
        { nombre: "azul", imagen: "productos/0026/4.jpeg" }
    ],
},
{
    id: 27,
    codigo: "0027",
    nombre: "supreme leather shoulder bag fw24 0027",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 510,
    precioMayoreo: 460,
    precioDistribuidor: 390,
    tallas: [],
    colores: ["negro","rojo","cafe","verde"],
    descripcion: "supreme leather shoulder bag fw24 de materiales de piel vacuna y forro de poliéster, de dimensiones compactas (18 cm x 23 cm) ideales para esenciales diarios, con 2 cierres y 2 compartimentos principales.",
    imagen: [
        'productos/0027/1.jpeg',
        'productos/0027/2.jpeg',
        'productos/0027/3.jpeg',
        'productos/0027/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0027/1.jpeg" },
        { nombre: "rojo", imagen: "productos/0027/2.jpeg" },
        { nombre: "cafe", imagen: "productos/0027/3.jpeg" },
        { nombre: "verde", imagen: "productos/0027/4.jpeg" }
    ],
},
{
    id: 28,
    codigo: "0028",
    nombre: "supreme logo waist bag fw23 0028",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 510,
    precioMayoreo: 460,
    precioDistribuidor: 390,
    tallas: [],
    colores: ["negro","gris","rojo","azul"],
    descripcion: "supreme logo waist bag fw23 de materiales de nylon ripstop cordura® con base laminada x-pac®, de 3 litros de capacidad, con 5 cierres y un compartimento principal que incluye bolsillos organizadores internos.",
    imagen: [
        'productos/0028/1.jpeg',
        'productos/0028/2.jpeg',
        'productos/0028/3.jpeg',
        'productos/0028/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0028/1.jpeg" },
        { nombre: "gris", imagen: "productos/0028/2.jpeg" },
        { nombre: "rojo", imagen: "productos/0028/3.jpeg" },
        { nombre: "azul", imagen: "productos/0028/4.jpeg" }
    ],
},
{
    id: 29,
    codigo: "0029",
    nombre: "supreme waist bag fw24 0029",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 510,
    precioMayoreo: 410,
    precioDistribuidor: 390,
    tallas: [],
    colores: ["negro","rojo","azul","cafe"],
    descripcion: "supreme waist bag fw24 de materiales de nylon cordura y malla, de 7 litros de capacidad, con tira reflectante superior, 2 cierres externos y correa ajustable para la cintura.",
    imagen: [
        'productos/0029/1.jpeg',
        'productos/0029/2.jpeg',
        'productos/0029/3.jpeg',
        'productos/0029/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0029/1.jpeg" },
        { nombre: "rojo", imagen: "productos/0029/2.jpeg" },
        { nombre: "azul", imagen: "productos/0029/3.jpeg" },
        { nombre: "cafe", imagen: "productos/0029/4.jpeg" }
    ],
},
{
    id: 30,
    codigo: "0030",
    nombre: "mochila supreme logo fw24 0030",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 860,
    precioMayoreo: 760,
    precioDistribuidor: 650,
    tallas: [],
    colores: ["negro","rojo","azul","beige"],
    descripcion: "mochila supreme logo fw24 de materiales de lona de nailon y paneles de malla, de 24 litros y capacidad de laptop de hasta 14 pulgadas, con cierre de cincha superior ajustable, 2 correas de compresión frontales y múltiples compartimentos internos organizadores.",
    imagen: [
        'productos/0030/1.jpeg',
        'productos/0030/2.jpeg',
        'productos/0030/3.jpeg',
        'productos/0030/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0030/1.jpeg" },
        { nombre: "rojo", imagen: "productos/0030/2.jpeg" },
        { nombre: "azul", imagen: "productos/0030/3.jpeg" },
        { nombre: "beige", imagen: "productos/0030/4.jpeg" }
    ],
},
{
    id: 31,
    codigo: "0031",
    nombre: "34 modelos de chamarra chrome hearts 0031",
    marca: "chrome-hearts",
    categoria: ["chamarras"],
    precioMenudeo: 860,
    precioMayoreo: 760,
    precioDistribuidor: 650,
    tallas: ["s","m","l","xl","2xl"],
    colores: ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35"],
    descripcion: "sudaderas y chamarras de felpa chrome hearts, de materiales de algodón con estampados gráficos.",
    imagen: [
        'productos//0031/1.jpeg',
        'productos/0031/2.jpeg',
        'productos/0031/3.jpeg',
        'productos/0031/4.jpeg',
        'productos/0031/5.jpeg',
        'productos/0031/6.jpeg',
        'productos/0031/7.jpeg',
        'productos/0031/8.jpeg',
        'productos/0031/9.jpeg',
        'productos/0031/10.jpeg',
        'productos/0031/11.jpeg',
        'productos/0031/12.jpeg',
        'productos/0031/13.jpeg',
        'productos/0031/14.jpeg',
        'productos/0031/15.jpeg',
        'productos/0031/16.jpeg',
        'productos/0031/17.jpeg',
        'productos/0031/18.jpeg',
        'productos/0031/19.jpeg',
        'productos/0031/20.jpeg',
        'productos/0031/21.jpeg',
        'productos/0031/22.jpeg',
        'productos/0031/23.jpeg',
        'productos/0031/24.jpeg',
        'productos/0031/25.jpeg',
        'productos/0031/26.jpeg',
        'productos/0031/27.jpeg',
        'productos/0031/28.jpeg',
        'productos/0031/29.jpeg',
        'productos/0031/30.jpeg',
        'productos/0031/31.jpeg',
        'productos/0031/32.jpeg',
        'productos/0031/33.jpeg',
        'productos/0031/34.jpeg',
        'productos/0031/35.jpeg'
    ],
    variantes: [
        { nombre: "1", imagen: "productos/0031/1.jpeg" },
        { nombre: "2", imagen: "productos/0031/2.jpeg" },
        { nombre: "3", imagen: "productos/0031/3.jpeg" },
        { nombre: "4", imagen: "productos/0031/4.jpeg" },
        { nombre: "5", imagen: "productos/0031/5.jpeg" },
        { nombre: "6", imagen: "productos/0031/6.jpeg" },
        { nombre: "7", imagen: "productos/0031/7.jpeg" },
        { nombre: "8", imagen: "productos/0031/8.jpeg" },
        { nombre: "9", imagen: "productos/0031/9.jpeg" },
        { nombre: "10", imagen: "productos/0031/10.jpeg" },
        { nombre: "11", imagen: "productos/0031/11.jpeg" },
        { nombre: "12", imagen: "productos/0031/12.jpeg" },
        { nombre: "13", imagen: "productos/0031/13.jpeg" },
        { nombre: "14", imagen: "productos/0031/6.jpeg" },
        { nombre: "15", imagen: "productos/0031/15.jpeg" },
        { nombre: "16", imagen: "productos/0031/16.jpeg" },
        { nombre: "17", imagen: "productos/0031/17.jpeg" },
        { nombre: "18", imagen: "productos/0031/18.jpeg" },
        { nombre: "19", imagen: "productos/0031/19.jpeg" },
        { nombre: "20", imagen: "productos/0031/20.jpeg" },
        { nombre: "21", imagen: "productos/0031/21.jpeg" },
        { nombre: "22", imagen: "productos/0031/22.jpeg" },
        { nombre: "23", imagen: "productos/0031/23.jpeg" },
        { nombre: "24", imagen: "productos/0031/24.jpeg" },
        { nombre: "25", imagen: "productos/0031/25.jpeg" },
        { nombre: "26", imagen: "productos/0031/26.jpeg" },
        { nombre: "27", imagen: "productos/0031/27.jpeg" },
        { nombre: "28", imagen: "productos/0031/28.jpeg" },
        { nombre: "29", imagen: "productos/0031/29.jpeg" },
        { nombre: "30", imagen: "productos/0031/30.jpeg" },
        { nombre: "31", imagen: "productos/0031/31.jpeg" },
        { nombre: "32", imagen: "productos/0031/32.jpeg" },
        { nombre: "33", imagen: "productos/0031/33.jpeg" },
        { nombre: "34", imagen: "productos/0031/34.jpeg" },
        { nombre: "35", imagen: "productos/0031/35.jpeg" }
    ],
},
{
    id: 32,
    codigo: "0032",
    nombre: "chaqueta de mezclilla chrome hearts ",
    marca: "chrome-hearts",
    link: "https://www.kakobuy.com/item/details?url=https%3A%2F%2Fdetail.1688.com%2Foffer%2F1042331290423.html%3Fsource_type%3Dimage",
    categoria: ["chaquetas"],
    precioMenudeo: 1210,
    precioMayoreo: 1110,
    precioDistribuidor: 920,
    tallas: ["s","m","l","xl"],
    colores: ["negro","blanco","azul","gris/azul","beige"],
    descripcion: "chamarra de mezclilla chrome hearts, de materiales de algodon con insignias de metal en la parte del pecho, el cuello y en la parte de atras con detalles de desgaste.",
    imagen: [
        'productos/0032/1.jpeg',
        'productos/0032/2.jpeg',
        'productos/0032/3.jpeg',
        'productos/0032/4.jpeg',
        'productos/0032/5.jpeg',
        'productos/0032/6.jpeg',
        'productos/0032/7.jpeg',
        'productos/0032/8.jpeg',
        'productos/0032/9.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0032/1.jpeg" },
        { nombre: "blanco", imagen: "productos/0032/5.jpeg" },
        { nombre: "azul", imagen: "productos/0032/7.jpeg" },
        { nombre: "gris/azul", imagen: "productos/0032/8.jpeg" },
        { nombre: "beige", imagen: "productos/0032/9.jpeg" }
    ],
},
{
    id: 33,
    codigo: "0033",
    nombre: "30 playeras chrome hearts ",
    marca: "chrome-hearts",
    link: "https://www.kakobuy.com/item/details?url=https%3A%2F%2Fdetail.1688.com%2Foffer%2F907203263279.html%3Fsource_type%3Dimage",
    categoria: ["playeras"],
    precioMenudeo: 580,
    precioMayoreo: 530,
    precioDistribuidor: 450,
    tallas: ["s","m","l","xl"],
    colores: ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"],
    descripcion: "playeras de algodon chrome hearts con diversos estampados",
    imagen: [
        'productos/0033/1.jpeg',
        'productos/0033/2.jpeg',
        'productos/0033/3.jpeg',
        'productos/0033/4.jpeg',
        'productos/0033/5.jpeg',
        'productos/0033/6.jpeg',
        'productos/0033/7.jpeg',
        'productos/0033/8.jpeg',
        'productos/0033/9.jpeg',
        'productos/0033/10.jpeg',
        'productos/0033/11.jpeg',
        'productos/0033/12.jpeg',
        'productos/0033/13.jpeg',
        'productos/0033/14.jpeg',
        'productos/0033/15.jpeg',
        'productos/0033/16.jpeg',
        'productos/0033/17.jpeg',
        'productos/0033/18.jpeg',
        'productos/0033/19.jpeg',
        'productos/0033/20.jpeg',
        'productos/0033/21.jpeg',
        'productos/0033/22.jpeg',
        'productos/0033/23.jpeg',
        'productos/0033/24.jpeg',
        'productos/0033/25.jpeg',
        'productos/0033/26.jpeg',
        'productos/0033/27.jpeg',
        'productos/0033/28.jpeg',
        'productos/0033/29.jpeg',
        'productos/0033/30.jpeg'
    ],
    variantes: [
        { nombre: "1", imagen: "productos/0033/1.jpeg" },
        { nombre: "2", imagen: "productos/0033/2.jpeg" },
        { nombre: "3", imagen: "productos/0033/3.jpeg" },
        { nombre: "4", imagen: "productos/0033/4.jpeg" },
        { nombre: "6", imagen: "productos/0033/6.jpeg" },
        { nombre: "7", imagen: "productos/0033/7.jpeg" },
        { nombre: "8", imagen: "productos/0033/8.jpeg" },
        { nombre: "9", imagen: "productos/0033/9.jpeg" },
        { nombre: "10", imagen: "productos/0033/10.jpeg" },
        { nombre: "11", imagen: "productos/0033/11.jpeg" },
        { nombre: "12", imagen: "productos/0033/12.jpeg" },
        { nombre: "13", imagen: "productos/0033/13.jpeg" },
        { nombre: "14", imagen: "productos/0033/14.jpeg" },
        { nombre: "15", imagen: "productos/0033/15.jpeg" },
        { nombre: "16", imagen: "productos/0033/16.jpeg" },
        { nombre: "17", imagen: "productos/0033/17.jpeg" },
        { nombre: "18", imagen: "productos/0033/18.jpeg" },
        { nombre: "19", imagen: "productos/0033/19.jpeg" },
        { nombre: "20", imagen: "productos/0033/20.jpeg" },
        { nombre: "21", imagen: "productos/0033/21.jpeg" },
        { nombre: "22", imagen: "productos/0033/22.jpeg" },
        { nombre: "23", imagen: "productos/0033/23.jpeg" },
        { nombre: "24", imagen: "productos/0033/24.jpeg" },
        { nombre: "25", imagen: "productos/0033/25.jpeg" },
        { nombre: "26", imagen: "productos/0033/26.jpeg" },
        { nombre: "27", imagen: "productos/0033/27.jpeg" },
        { nombre: "28", imagen: "productos/0033/28.jpeg" },
        { nombre: "29", imagen: "productos/0033/29.jpeg" },
        { nombre: "30", imagen: "productos/0033/30.jpeg" }
    ],
},
{
    id: 31,
    codigo: "0031",
    nombre: "34 modelos de chamarra chrome hearts",
    marca: "chrome-hearts",
    categoria: ["chamarras"],
    precioMenudeo: 860,
    precioMayoreo: 760,
    precioDistribuidor: 650,
    tallas: ["s","m","l","xl","2xl"],
    colores: ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35"],
    descripcion: "sudaderas y chamarras de felpa chrome hearts, de materiales de algodón con estampados gráficos.",
    imagen: [
        'productos/chrome-hearts/0031/1.jpeg',
        'productos/chrome-hearts/0031/2.jpeg',
        'productos/chrome-hearts/0031/3.jpeg',
        'productos/chrome-hearts/0031/4.jpeg',
        'productos/chrome-hearts/0031/5.jpeg',
        'productos/chrome-hearts/0031/6.jpeg',
        'productos/chrome-hearts/0031/7.jpeg',
        'productos/chrome-hearts/0031/8.jpeg',
        'productos/chrome-hearts/0031/9.jpeg',
        'productos/chrome-hearts/0031/10.jpeg',
        'productos/chrome-hearts/0031/11.jpeg',
        'productos/chrome-hearts/0031/12.jpeg',
        'productos/chrome-hearts/0031/13.jpeg',
        'productos/chrome-hearts/0031/14.jpeg',
        'productos/chrome-hearts/0031/15.jpeg',
        'productos/chrome-hearts/0031/16.jpeg',
        'productos/chrome-hearts/0031/17.jpeg',
        'productos/chrome-hearts/0031/18.jpeg',
        'productos/chrome-hearts/0031/19.jpeg',
        'productos/chrome-hearts/0031/20.jpeg',
        'productos/chrome-hearts/0031/21.jpeg',
        'productos/chrome-hearts/0031/22.jpeg',
        'productos/chrome-hearts/0031/23.jpeg',
        'productos/chrome-hearts/0031/24.jpeg',
        'productos/chrome-hearts/0031/25.jpeg',
        'productos/chrome-hearts/0031/26.jpeg',
        'productos/chrome-hearts/0031/27.jpeg',
        'productos/chrome-hearts/0031/28.jpeg',
        'productos/chrome-hearts/0031/29.jpeg',
        'productos/chrome-hearts/0031/30.jpeg',
        'productos/chrome-hearts/0031/31.jpeg',
        'productos/chrome-hearts/0031/32.jpeg',
        'productos/chrome-hearts/0031/33.jpeg',
        'productos/chrome-hearts/0031/34.jpeg',
        'productos/chrome-hearts/0031/35.jpeg'
    ],
    variantes: [
        { nombre: "1", imagen: "productos/chrome-hearts/0031/1.jpeg" },
        { nombre: "2", imagen: "productos/chrome-hearts/0031/2.jpeg" },
        { nombre: "3", imagen: "productos/chrome-hearts/0031/3.jpeg" },
        { nombre: "4", imagen: "productos/chrome-hearts/0031/4.jpeg" },
        { nombre: "5", imagen: "productos/chrome-hearts/0031/5.jpeg" },
        { nombre: "6", imagen: "productos/chrome-hearts/0031/6.jpeg" },
        { nombre: "7", imagen: "productos/chrome-hearts/0031/7.jpeg" },
        { nombre: "8", imagen: "productos/chrome-hearts/0031/8.jpeg" },
        { nombre: "9", imagen: "productos/chrome-hearts/0031/9.jpeg" },
        { nombre: "10", imagen: "productos/chrome-hearts/0031/10.jpeg" },
        { nombre: "11", imagen: "productos/chrome-hearts/0031/11.jpeg" },
        { nombre: "12", imagen: "productos/chrome-hearts/0031/12.jpeg" },
        { nombre: "13", imagen: "productos/chrome-hearts/0031/13.jpeg" },
        { nombre: "14", imagen: "productos/chrome-hearts/0031/6.jpeg" },
        { nombre: "15", imagen: "productos/chrome-hearts/0031/15.jpeg" },
        { nombre: "16", imagen: "productos/chrome-hearts/0031/16.jpeg" },
        { nombre: "17", imagen: "productos/chrome-hearts/0031/17.jpeg" },
        { nombre: "18", imagen: "productos/chrome-hearts/0031/18.jpeg" },
        { nombre: "19", imagen: "productos/chrome-hearts/0031/19.jpeg" },
        { nombre: "20", imagen: "productos/chrome-hearts/0031/20.jpeg" },
        { nombre: "21", imagen: "productos/chrome-hearts/0031/21.jpeg" },
        { nombre: "22", imagen: "productos/chrome-hearts/0031/22.jpeg" },
        { nombre: "23", imagen: "productos/chrome-hearts/0031/23.jpeg" },
        { nombre: "24", imagen: "productos/chrome-hearts/0031/24.jpeg" },
        { nombre: "25", imagen: "productos/chrome-hearts/0031/25.jpeg" },
        { nombre: "26", imagen: "productos/chrome-hearts/0031/26.jpeg" },
        { nombre: "27", imagen: "productos/chrome-hearts/0031/27.jpeg" },
        { nombre: "28", imagen: "productos/chrome-hearts/0031/28.jpeg" },
        { nombre: "29", imagen: "productos/chrome-hearts/0031/29.jpeg" },
        { nombre: "30", imagen: "productos/chrome-hearts/0031/30.jpeg" },
        { nombre: "31", imagen: "productos/chrome-hearts/0031/31.jpeg" },
        { nombre: "32", imagen: "productos/chrome-hearts/0031/32.jpeg" },
        { nombre: "33", imagen: "productos/chrome-hearts/0031/33.jpeg" },
        { nombre: "34", imagen: "productos/chrome-hearts/0031/34.jpeg" },
        { nombre: "35", imagen: "productos/chrome-hearts/0031/35.jpeg" }
    ],
},
{
    id: 35,
    codigo: "0035",
    nombre: "supreme backpack fw21 0035",
    marca: "supreme",
    categoria: ["mochilas"],
    precioMenudeo: 900,
    precioMayoreo: 800,
    precioDistribuidor: 700,
    tallas: [],
    colores: ["negro","morado","naranja","verde"],
    descripcion: "supreme backpack fw21 de materiales de nailon cordura ripstop, de 20 litros y capacidad de laptop de 15 pulgadas, con 3 cierres y 4 compartimentos",
    imagen: [
        'productos/0035/1.jpeg',
        'productos/0035/2.jpeg',
        'productos/0035/3.jpeg',
        'productos/0035/4.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/0035/1.jpeg" },
        { nombre: "morado", imagen: "productos/0035/2.jpeg" },
        { nombre: "naranja", imagen: "productos/0035/3.jpeg" },
        { nombre: "verde", imagen: "productos/0035/4.jpeg" }
    ],
    guiaTallas: "productos/0035/guia.jpeg"
},
{
    id: 1002,
    codigo: "1002",
    nombre: "sudadera supreme gran logo en la cintura 1002",
    marca: "supreme",
    categoria: ["sudaderas"],
    precioMenudeo: 1660,
    precioMayoreo: 1560,
    precioDistribuidor: 1270,
    tallas: ["s","m","l","xl"],
    colores: ["azul","negro"],
    descripcion: "sudadera supreme big logo zip up hoodie, de algodón pesado con cierre central de cremallera, caracterizada por un enorme gráfico de supreme impreso en blanco que envuelve toda la parte inferior de la prenda, bolsillo frontal tipo canguro y cordón ajustable en la capucha.",
    imagen: [
        'productos/1002/1.jpeg',
        'productos/1002/2.jpeg',
        'productos/1002/3.jpeg',
        'productos/1002/4.jpeg',
        'productos/1002/5.jpeg'
    ],
    variantes: [
        { nombre: "azul", imagen: "productos/1002/2.jpeg" }
    ],
    guiaTallas: "productos/1002/guia.jpeg"
},
{
    id: 1003,
    codigo: "1003",
    nombre: "sudadera supreme × maison margiela 1003",
    marca: "supreme, mm6",
    categoria: ["sudadera"],
    precioMenudeo: 1690,
    precioMayoreo: 1590,
    precioDistribuidor: 1290,
    tallas: ["s","m","l","xl"],
    colores: ["negro","verde","gris"],
    descripcion: "sudadera supreme × mm6 maison margiela, de algodón grueso y cremallera metálica central, con gráficos de tipografía colegial superpuestos en el pecho con el año 1994, doble etiqueta de la colaboración en el cuello, bordado numérico negro en la manga y capucha forrada con un llamativo estampado de calaveras con fuego.",
    imagen: [
        'productos/1003/1.jpeg',
        'productos/1003/2.jpeg',
        'productos/1003/3.jpeg',
        'productos/1003/4.jpeg',
        'productos/1003/5.jpeg',
        'productos/1003/6.jpeg',
        'productos/1003/7.jpeg',
        'productos/1003/8.jpeg'
    ],
    variantes: [
        { nombre: "negro", imagen: "productos/1003/1.jpeg" },
        { nombre: "verde", imagen: "productos/1003/7.jpeg" },
        { nombre: "gris", imagen: "productos/1003/5.jpeg" }
    ],
    guiaTallas: "productos/1003/guia.jpeg"
},
{
    id: 2000,
    codigo: "2000",
    nombre: "mochila nike elite",
    marca: "nike",
    categoria: ["mochilas"],
    precioMenudeo: 790,
    precioMayoreo: 680,
    precioDistribuidor: 590,
    tallas: [],
    colores: ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19"],
    descripcion: "la mochila nike elite cuenta con una capacidad aproximada de 32 l, compartimento acolchado para laptop de hasta 15.6 pulgadas, amplio espacio para libros, ropa o equipo deportivo, bolsillos laterales para botella, compartimentos con cierre para una mejor organización, material resistente y correas acolchadas y ajustables que brindan mayor comodidad durante el uso diario.",
    imagen: [
        'productos/2000/1.jpeg',
        'productos/2000/2.jpeg',
        'productos/2000/3.jpeg',
        'productos/2000/4.jpeg',
        'productos/2000/5.jpeg',
        'productos/2000/6.jpeg',
        'productos/2000/7.jpeg',
        'productos/2000/8.jpeg',
        'productos/2000/9.jpeg',
        'productos/2000/10.jpeg',
        'productos/2000/11.jpeg',
        'productos/2000/12.jpeg',
        'productos/2000/13.jpeg',
        'productos/2000/14.jpeg',
        'productos/2000/15.jpeg',
        'productos/2000/16.jpeg',
        'productos/2000/17.jpeg',
        'productos/2000/18.jpeg',
        'productos/2000/19.jpeg'
    ],
    variantes: [
        { nombre: "1", imagen: "productos/2000/1.jpeg" },
        { nombre: "2", imagen: "productos/2000/2.jpeg" },
        { nombre: "3", imagen: "productos/2000/3.jpeg" },
        { nombre: "4", imagen: "productos/2000/4.jpeg" },
        { nombre: "5", imagen: "productos/2000/5.jpeg" },
        { nombre: "6", imagen: "productos/2000/6.jpeg" },
        { nombre: "7", imagen: "productos/2000/7.jpeg" },
        { nombre: "8", imagen: "productos/2000/8.jpeg" },
        { nombre: "9", imagen: "productos/2000/9.jpeg" },
        { nombre: "10", imagen: "productos/2000/10.jpeg" },
        { nombre: "11", imagen: "productos/2000/11.jpeg" },
        { nombre: "12", imagen: "productos/2000/12.jpeg" },
        { nombre: "13", imagen: "productos/2000/13.jpeg" },
        { nombre: "14", imagen: "productos/2000/14.jpeg" },
        { nombre: "15", imagen: "productos/2000/15.jpeg" },
        { nombre: "16", imagen: "productos/2000/16.jpeg" },
        { nombre: "17", imagen: "productos/2000/17.jpeg" },
        { nombre: "18", imagen: "productos/2000/18.jpeg" },
        { nombre: "19", imagen: "productos/2000/19.jpeg" }
    ],
},
{
    id: 2003,
    codigo: "2003",
    nombre: "sudadera bape shark",
    marca: "bape",
    categoria: ["sudadera"],
    precioMenudeo: 1250,
    precioMayoreo: 1150,
    precioDistribuidor: 950,
    tallas: ["m","l","xl","2xl","3xl"],
    colores: ["azul","verde con cafe claro","morado con rosa","negro con gris","negro con blanco","rojo","rosa","verde fuerte"],
    descripcion: "sudadera bape shark confeccionada en algodón de alta calidad con tejido grueso y resistente, corte regular, capucha completa con cierre, bolsillo tipo canguro y puños y cintura acanalados para un mejor ajuste. su diseño icónico ofrece comodidad, durabilidad y un estilo urbano premium, ideal para el uso diario.",
    imagen: [
        'productos/2003/1.jpeg',
        'productos/2003/2.jpeg',
        'productos/2003/3.jpeg',
        'productos/2003/4.jpeg',
        'productos/2003/5.jpeg',
        'productos/2003/6.jpeg',
        'productos/2003/7.jpeg',
        'productos/2003/8.jpeg'
    ],
    variantes: [
        { nombre: "azul", imagen: "productos/2003/1.jpeg" },
        { nombre: "verde con cafe claro", imagen: "productos/2003/2.jpeg" },
        { nombre: "morado con rosa", imagen: "productos/2003/3.jpeg" },
        { nombre: "negro con gris", imagen: "productos/2003/4.jpeg" },
        { nombre: "negro con blanco", imagen: "productos/2003/5.jpeg" },
        { nombre: "rojo", imagen: "productos/2003/6.jpeg" },
        { nombre: "rosa", imagen: "productos/2003/7.jpeg" },
        { nombre: "verde fuerte", imagen: "productos/2003/8.jpeg" }
    ],
    guiaTallas: "productos/2003/guia.jpeg"
},
];